# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Vasa Tech Blog
tagline:             'Blog'
description:         'Tech blog for all-things Web'
url:                 http://www.vasanthk.com/
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Vasa Tech Blog
  url:               https://twitter.com/vasanth_k
  email:             vasanth.citrix@gmail.com

# Custom vars
version:             1.0.0
